# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           pretty

# Setup
title:               Phpizza
tagline:             Minimal is good
description:         I'm an insane web developer.
url:                 https://alanaktion.github.io
baseurl:             /

# Pagination
gems:                [jekyll-paginate]
paginate:            7
paginate_path:       page:num

# About/contact
author:
  name:              Alan Hardman
  url:               https://phpizza.com
  email:             alan@phpizza.com
