# Dependencies
markdown:            kramdown
highlighter:         rouge

# GFM
kramdown:
  input:             GFM

# Permalinks
permalink:           /:year/:month/:day/:title/

# Setup
title:               Phピザ
tagline:             最小限は良いです
tagline_romanji:     Saishōgen wa yoidesu
description:         僕はウェブ開発者。
description_romanji: Boku wa u~ebu kaihatsu-sha.
url:                 https://blog.phpizza.com

# SCSS
sass:
  style: compressed
  sass_dir: _scss

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Pagination
paginate:            10
paginate_path:       page:num

# About/contact
author:
  name:              ハダマンカイト
  url:               https://phpizza.com
  email:             alan+jp@phpizza.com

# Workaround npm issue
exclude:             ["reveal/node_modules"]
