# Dependencies
markdown:            kramdown
highlighter:         rouge

# GFM
kramdown:
  input:             GFM

# Permalinks
permalink:           /:year/:month/:day/:title/

# Setup
title:               Phpizza
tagline:             Minimal is good
description:         I'm an insane web developer.
url:                 https://blog.phpizza.com

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Pagination
paginate:            5
paginate_path:       page:num

# About/contact
author:
  name:              Alan Hardman
  url:               https://phpizza.com
  email:             alan@phpizza.com

# Ignore node stuff
exclude:
  - "node_modules"
  - "_pdf"
