# Dependencies
markdown:            kramdown
highlighter:         rouge

# GFM
kramdown:
  input:             GFM

# Permalinks
permalink:           /:year/:month/:day/:title/

# Setup
title:               Phpizza
tagline:             Mínimo es bueno
description:         Soy un desarrollador loco
url:                 https://es.phpizza.com

# SCSS
sass:
  style: compressed
  sass_dir: _scss

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Pagination
paginate:            10
paginate_path:       page:num

# About/contact
author:
  name:              Alan Hardman
  url:               https://phpizza.com
  email:             alan@phpizza.com

# Workaround npm issue
exclude:             ["reveal/node_modules"]
